### ISSUE TITLE
Unable to generate output

### ISSUE THREAD

**Issue by martinpesout** [milanowicz/generator-html5-page#2]
Hi, 

I have a problem with this generator. My config is

```
Welcome to the HTML5 Website Skeleton Generator!
[?] What do you want to call your Website? Test template
[?] What is your description for it? Test template based on Zurb Foundation 5 framework
[?] Enter your Project Directory: website
[?] Enter your Distribute Directory: public
[?] Enter your Bower Resource Directory: bower_components
[?] Which CSS extension language should be GruntJS supported? SASS - http://sass-lang.com/
[?] Would you like to develop with a CSS Framework? Foundation - http://foundation.zurb.com/
[?] Which jQuery Version should it be? - http://jquery.com/ Version 2.1.x
[?] What Software would you like to have for your new project? Font Awesome - http://fortawesome.github.io/Font-Awesome/, FitText.js - https://github.com/Milanowicz/FitText.js
[?] What should be supported by GruntJS for you? 
[?] What should GruntJS do? Run grunt serve command
```

And after confirmation I'll get next error

```
undefined:44
 } if (LessCollection) { ;
       ^
ReferenceError: LessCollection is not defined
    at eval (eval at template (/usr/local/lib/node_modules/generator-html5-page/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6305:22), <anonymous>:44:8)
    at Html5pagegenerator.underscore [as _engine] (/usr/local/lib/node_modules/generator-html5-page/node_modules/yeoman-generator/lib/util/engines.js:32:30)
    at Html5pagegenerator.engine (/usr/local/lib/node_modules/generator-html5-page/node_modules/yeoman-generator/lib/actions/actions.js:303:10)
    at Html5pagegenerator.template (/usr/local/lib/node_modules/generator-html5-page/node_modules/yeoman-generator/lib/actions/actions.js:281:15)
    at Html5pagegenerator.app (/usr/local/lib/node_modules/generator-html5-page/app/index.js:292:10)
    at /usr/local/lib/node_modules/generator-html5-page/node_modules/yeoman-generator/lib/base.js:341:43
    at /usr/local/lib/node_modules/generator-html5-page/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /usr/local/lib/node_modules/generator-html5-page/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/usr/local/lib/node_modules/generator-html5-page/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at /usr/local/lib/node_modules/generator-html5-page/node_modules/yeoman-generator/node_modules/async/lib/async.js:145:25
```

Is it possible to fix it? Thanks a lot

**Comment by milanowicz** [comment]
Hi,
i test it and fixed the errors for Sass. I update the version and you can update the generator to v0.0.8.
It should work now, when not, then I look into it :)

**Comment by martinpesout** [comment]
Thanks a lot. It works like a charm now :-)
